import pkg from './package.json'
import buble from 'rollup-plugin-buble'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import replace from 'rollup-plugin-replace'

var target = '// Generated by CoffeeScript 1.12.2'
var replacement = `${target}\r\n/* istanbul ignore next */`

export default {
  input: 'src/dynamica.js',
  output: [
    { file: pkg.main, format: 'umd', name: 'Animation' },
    { file: pkg.module, format: 'es' }
  ],
  plugins: [
    buble(),
    nodeResolve(),
    commonjs(),
    replace({
      delimiters: ['', ''],
      [target]: replacement
    })
  ]
}
