import babel from 'rollup-plugin-babel'
import nodeResolve from 'rollup-plugin-node-resolve'
import commonjs from 'rollup-plugin-commonjs'
import replace from 'rollup-plugin-replace'

var target = '// Generated by CoffeeScript 1.12.2'
var replacement = `${target}\r\n/* istanbul ignore next */`

export default {
  moduleName: 'Animation',
  entry: 'src/dynamica.js',
  dest: 'dist/dynamica.js',
  format: 'umd',
  plugins: [
    babel(),
    nodeResolve(),
    commonjs(),
    replace({
      [target]: replacement
    })
  ]
}
